version: "3.8"

services:
  backend:
    image: node:16
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/home/node/app
    depends_on:
      - database
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start"

  database:
    image: postgres:13
    restart: always
    volumes:
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  frontend:
    image: node:16
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    #depends_on:
    ports:
      - 80:3000
    command: sh -c "npm install && npm run start"
    stdin_open: true

  adminer:
    image: adminer:4.7.7 # replace by standalone when bug on export will be resolved
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
    ports:
      - 8080:8080